name: "CD"

on:
  push:
    branches:
      - master

jobs:
  validate:
    name: "Check Build"
    uses: ./.github/workflows/validate.yml

  publish:
    name: "Publish Crate"
    needs: validate
    uses: ./.github/workflows/publish.yml
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}