name: "CI"

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "doc/**"
  push:
    branches: master

jobs:
  validate:
    name: "Check Build"
    uses: ./.github/workflows/actions/validate.yml

  publish:
    name: "Publish Crate"
    permissions:
      contents: read
    uses: ./.github/workflows/actions/publish.yml
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}