name: Publish

on:
  workflow_call:
    secrets:
      CRATES_IO_TOKEN:
        required: true

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: |
          CURRENT_VER=$(cat Cargo.toml                                    \
            | grep 'version'                                              \
            | grep --only-matching '[[:digit:]].[[:digit:]].[[:digit:]]')

          PUBLISHED_VER=$(cargo search essentia-rs --color=never          \
            | grep --only-matching '[[:digit:]].[[:digit:]].[[:digit:]]')

          SMALLER_VER=$(echo "$PUBLISHED_VER\n$EXISTING_VER"              \
            | sort -V                                                     \
            | head -1)

          if [ $SMALLER_VER = $PUBLISHED_VER ]; then
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "should_publish=false" >> $GITHUB_ENV
          fi

      - uses: actions-rs/cargo@v1
        if: ${{ env.should_publish == "true" }}
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}