name: Publish

on:
  workflow_call:
    secrets:
      CRATES_IO_TOKEN:
        required: true

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout src"

      - uses: actions-rs/toolchain@v1
        name: "Setup toolchain"
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: "Check if should publish"
        run: |
          CURRENT_VER=$(cat Cargo.toml                                    \
            | grep 'version'                                              \
            | grep --only-matching '[[:digit:]].[[:digit:]].[[:digit:]]'  \
            | tr -d '\n')
          echo "Detected current package version of $CURRENT_VER"

          PUBLISHED_VER=$(cargo search essentia-rs --quiet --color=never  \
            | grep --only-matching '[[:digit:]].[[:digit:]].[[:digit:]]'  \
            | tr -d '\n')
          echo "Detected current published version of $PUBLISHED_VER"

          if [ $CURRENT_VER = $PUBLISHED_VER ]; then
            echo "Current version is equal to published: should_publish=false"
            exit 0
          fi

          SMALLER_VER=$(echo "$PUBLISHED_VER\n$EXISTING_VER"              \
            | sort -V                                                     \
            | head -1                                                     \
            | tr -d '\n')
          echo "Smaller version is: $SMALLER_VER"

          if [ $SMALLER_VER = $PUBLISHED_VER ]; then
            echo "Published version is older: should_publish=true"
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "Published version is newer: should_publish=false"
            echo "should_publish=false" >> $GITHUB_ENV
          fi

      - name: "Publish"
        uses: actions-rs/cargo@v1
        if: env.should_publish == 'true'
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}