name: Validate

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "doc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    needs: validate_release_version
    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          cargo test -- --nocapture