name: Validate

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "doc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmr, clippy
          toolchain: nightly

      - name: Cargo Test
        run: cargo test -- --nocapture